Connect to API
Have-Samuel/book-store pull request #4
Opened 2022-05-05 20:04 UTC by Have-Samuel

In connecting to API: 
- Used the concept of state management.
- Used store, actions, and reducers in React.
- Connected React and Redux.
- Connected an existing API via Redux and use the data to display something in a UI.

2022-05-05 20:50 UTC, mikethreels requested changes
Hi Have, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️ 
- [ ] the project is not working as expected the user is not able to add a book to the list, I've left a few inline comments but keep in mind that updating those suggestions might give you other errors, I advise you when testing to put some console.log() in your code to see what it is returning.
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-05 20:50 UTC, mikethreels commented on src/redux/books/books.js
> +      return [...state, ...action.payload];
- [ ] you are using the spread operator as if you're adding to an array but the initialState is an object that's why the state doesn't get updated, what you can do to fix this is to change the initial state to an array and `return [...state, action.payload]`

2022-05-05 20:50 UTC, mikethreels commented on src/redux/books/books-api.js
> +    return books;
- [ ] you are returning the books array here but this always will be an empty array as set in line 10

2022-05-06 06:13 UTC, CollinsTatang approved these changes
# Approved 👏  

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### **Congratulations!** 🎉 
![image](https://user-images.githubusercontent.com/55596970/158098566-50966056-ce3d-4c4b-aac3-cce7a7d107fb.png)



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @CollinsTatang in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-05-06 06:15 UTC, merged